### ISSUE TITLE
How to use this work for pose estimation on novel objects?

### ISSUE THREAD

**Issue by mikkeljakobsen** [nv-nguyen/template-pose#3]
Thanks for an interesting paper!

Is it possible to use this work for pose estimation of novel objects given that I have a textured CAD model? I managed to produce the template images using your BlenderProc script, but I can't figure out how to proceed from there. Can you provide instructions?

**Comment by nv-nguyen** [comment]
Hi @mikkeljakobsen, very sorry for the long delay, I was out of the office. Here are some main steps for estimating 3D poses of novel objects given their textured CAD mode by following the setting of Implicit [32]:

**- Step 1 (Rendering)**: Rendering synthetic templates with BlenderProc script. We can use either [602 viewpoints (coarse version)](https://github.com/nv-nguyen/template-pose/blob/ce1ffead1887b54efc8031e8e2442ba884e512ec/data/render_templates.py#L74) or [2.562 viewpoints (dense version)](https://github.com/nv-nguyen/template-pose/blob/ce1ffead1887b54efc8031e8e2442ba884e512ec/data/render_templates.py#L75);

**- Step 2 (In-plane rotation)**: Applying in-plane rotations for each template. Indeed,  only 2 degrees of freedom are defined with a 3D sphere (azimuth and elevation). To cover all the 3D rotations, we need to apply the third one, in-plane rotation (or 2D rotation) for each template. In the paper, [we followed [32] and used 36 angles (with 10 degrees of difference);](https://github.com/nv-nguyen/template-pose/blob/main/lib/datasets/tless/dataloader_template.py#L47);

**- Step 3 (Cropping)**: After step 2, we will have 21.672 templates (coarse version) and 92.232 templates (dense version) that we can easily get a 2D bounding box for each of them by doing img.getbbox() (images loaded with PIL library). For the real query image, the 2D bounding box should be given by the user in order to crop the correct region and focus on the correct object. For few (synthetic)-shot object detection, please take a look at section 3.1 of [this paper](https://arxiv.org/pdf/2203.15533.pdf);

**- Step 4 (Nearest neighbors search)**: Searching the best template with our local similarity and pre-trained deep network (I suggested using [ResNet50 trained on LINEMOD](https://drive.google.com/drive/u/1/folders/11SQYPrG3pX31Qszf8R13s7Aaa5MO57lb), i.e LM_ResNet50_split1 or LM_ResNet50_split2 or LM_ResNet50_split3). Once the best template is found, we can deduce the 3D rotation (+3D translation from the perspective formula of SSD-6D [18]) for novel objects.

I will try to upload a notebook for the demo soon. Hopefully, it will be useful!

**Comment by monajalal** [comment]
@nv-nguyen 
https://github.com/nv-nguyen/template-pose/blob/main/lib/datasets/tless/dataloader_template.py#L47
is not accessible

![Screenshot from 2023-11-13 14-01-50](https://github.com/nv-nguyen/template-pose/assets/1892917/3c5e30e0-d13f-4102-9c50-3f23615ef329)
