### ISSUE TITLE
Template number for train and test

### ISSUE THREAD

**Issue by qifengluo** [nv-nguyen/template-pose#37]
Hi, I want to train and test on the less dataset, but there seems to be an issue with the number of templates.

I see that the number of rendered templates for level 2 and level 3 is 642 and 2562 (viewpoints), respectively. Will the performance of the trained model be worse than using a level3 template, as the default parameter during training is to use a level2 template?

When testing, the number of templates should be the same as AAE's 92232, but there is no relevant templates. Is it enough to only use the number of templates at level 2 or level 3 for testing?

**Comment by nv-nguyen** [comment]
1. "Will the performance of the trained model be worse than using a level3 template, as the default parameter during training is to use a level2 template?"
-> I expect the performance to be better when training and testing with higher number of templates but I did not try with level3 for training. I always use level2 template since it was done in the baselines.

2. "Is it enough to only use the number of templates at level 2 or level 3 for testing?"
-> Yes, using level2 templates for both training and testing should be enough. As shown in Table 3 with results on T-LESS, I don't see any significant improvements when using level3 instead of level2.

Hope it helps!

**Comment by qifengluo** [comment]
Thank you for your reply!
 I see that the number of templates in Table 3 are 92k and 21k, which is much higher than the number of templates in level 2 and level 3. Does it require sampling in plane rotation to render more templates in order to obtain the same number of templates as Table 3 to obtain the same test results as Table 3?

**Comment by nv-nguyen** [comment]
It is because in the setting with T-LESS, we also need to sample in-plane rotation (or 2D rotation) which is 36 angles (10 degrees each). So in total, 642*36=23 112 templates for level 2 and 2562*36= 92 232 templates for level 3.

**Comment by qifengluo** [comment]
I just found the code for in-plane rotation (rgb=rgb. rotate (in-plane)). But the results I tested with the downloaded checkpoint are much worse than those in the article, isn't that the final checkpoint. Could you provide the final checkpoint? I would like to conduct an evaluation experiment. 
Thank you.

**Comment by nv-nguyen** [comment]
This is the final checkpoint. Please share the results here if you have any issue with the results.

For any issue, you can try with the old codebase where everything works smoothly (but the code is less clean):
`git checkout 50a1087`

**Comment by qifengluo** [comment]
OK，I will try again. Thanks!

**Comment by qifengluo** [comment]
Hi, there is a bug : AttributeError: 'FeatureExtractor' object has no attribute 'obj_symmetry'.  I set model.metric_eval = "geodesic" in test_tless.py.
