### ISSUE TITLE
The Acc15 of tless dataset

### ISSUE THREAD

**Issue by qifengluo** [nv-nguyen/template-pose#38]
Hi,  I have some questions about Acc15 of tless datasets.
1. I evaluated the Acc15 of the tless dataset as test_lm.py, but the results were not very good.  I only used test_tless.py and changed the parameters according to the settings in test_lm.py 
![test](https://github.com/nv-nguyen/template-pose/assets/71620227/891587f9-1c14-4d2d-987b-ec299baedee7)
The Acc15 of each object is:
![acc15](https://github.com/nv-nguyen/template-pose/assets/71620227/37d7f9e4-66ae-4409-85e6-bc01b188bc61)
I don't know what's wrong?!
2. In fact, this type of template matching method is only used to estimate the attitude. The best way to evaluate the attitude is to use so3_relative-angle_with_symmetry. Using error_vsd also requires additional methods to estimate the translation vector, which to some extent cannot truly reflect the matching accuracy.

**Comment by nv-nguyen** [comment]
1. It is because the symmetry in T-LESS is not 90 degrees, 180 degrees around up axis as in LINEMOD. You can visualize qualitatively the results to check.

2. What do you mean by "attitude"? Our method estimates fully the rotation (azimuth, elevation, inplane) for T-LESS. It does not make sense to evaluate the accuracy on T-LESS with  so3_relative-angle_with_symmetry due to the object symmetry (more details in [Section 2 of BOP 2018 report](https://cmp.felk.cvut.cz/~hodanto2/data/hodan2018bop.pdf)).
