### ISSUE TITLE
implementation details

### ISSUE THREAD

**Issue by dingdingcai** [nv-nguyen/template-pose#4]
Hi Van-Nguyen,

Thanks for the excellent work! But I have a few questions about the implementation details.

1). How can we properly crop the target object from an RGB image? Or how did you know the 2D location and the size (even the in-plane rotation angle) of the object bounding box used for cropping the object?   In my understanding, you need to use the ground truth object 6D pose to determine the object's 2D projection center and the cropping size, right?

2). For creating the templates, how did you define the (virtual) camera distance to the object (or the diameter of the viewpoint sphere)? As I know, different objects have different sizes, the camera distance will affect the scale of the object in the rendered images.

3). For the LM dataset, as mentioned in the supplementary material, the object in-plane rotation will be ignored. What does it mean? Do you mean, for each crop, the ground truth in-plane rotation is assumed to be known and we only estimate the object's viewpoint (out-of-plane rotation )?

Looking forward to your reply and thank you very much!

**Comment by nv-nguyen** [comment]
Hi @dingdingcai, thanks for reaching out and I am very sorry for the long delay! Here is my answer to each of your questions:

 1. Yes, we need to know 6D pose to get correct 2D projection center and the cropping size for LINEMOD’s images. This setting of [2, 39] is not very helpful in practice but it allows us to understand the limitation of global representation [2, 39]. For more practical settings, we suggest using the setting of T-LESS as done in [31, 32] which requires only 2D bounding box for the input images.

2. We followed [2] by setting the translation as [0, 0, 400] (cm) for all the objects. Please note that as long as objects appear approximately correct in the rendered images (i.e objects are neither truncated nor so small), the scale of the object in the rendered images should not significantly change quantitative results on LINEMOD and T-LESS datasets since:
 
- For LINEMOD, we crop the images by using a 3D box (40 cm in each dimension) centered at object. This cropping remove the scale problem (i.e using rendering with translation=[0, 0, 400] (cm) or with translation=[0, 0, 500] (cm) will yield approximately same cropped images). Besides, we do not evaluate the translation on LINEMOD; 

- For T-LESS, we crop the images by using the GT 2D bounding box (then resize) and ajust the predicted translation with the size of GT 2D bounding boxes (via perspective formula of SSD-6D [18]). So, the VSD score depends mainly on the predicted rotation.

3. Yes, we only estimate the object's viewpoint (out-of-plane rotation) **and ID of object**. As said in the first point, this setting (from [2, 39]) is not very helpful in practice compared to the setting of T-LESS [31, 32].

I hope this helps!

**Comment by dingdingcai** [comment]
Now I completely understood and thank you very much for the details!
