### ISSUE TITLE
If this mothod can be adapt to other dataset?

### ISSUE THREAD

**Issue by Salvation-HUST** [nv-nguyen/template-pose#5]
@nv-nguyen
Thanks for this interesting paper!!!

I want to know if I have a dataset which is composed by other strong texture models such as car, desk, whether I can use this method mentioned by your great paper to estimate the pose?  

And another problem I find is that I can run the training code on LINEMOD but can't run on TLESS, and the error is as follows.

Traceback (most recent call last):
  File "train_tless.py", line 107, in <module>
    train_loss = training_utils.train(train_data=datasetLoader["train"],
  File "/home/rlk/template-pose-main/lib/datasets/tless/training_utils.py", line 64, in train
    tb_logger.add_scalar_dict_list('loss', [{'train_loss': meter_train_loss.avg,
TypeError: add_scalar_dict_list() got an unexpected keyword argument 'step'

**Comment by nv-nguyen** [comment]
Hi @Salvation-HUST,
 
Thanks for your interest in our paper!

1. Of course, it would be better if you have a strong texture since it will be easier for the network to estimate the similarity based on the texture of objects.

2. I fixed the error (just remove “step"). Thanks for pointing it out!

Don’t hesitate to ping me (here or by email) for any additional questions!
